### ISSUE TITLE
Add flask to project

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/forum123#4]
After we've created a basic project layout (issue https://github.com/EugeneTurkin/forum123/issues/2) we can go further and add `flask` to our project.

In the scope of this task we need to add `flask` to our project and write a simple "Hello world" page to test that everything works.

Steps to do:
- add `flask` to `requirements.txt` and install it locally
- write a simple "Hello world" page, like this:
```python
@app.route('/index')
def index():
    return "Hello, World!"
```
- run application locally and test that "Hello world" page works
- add information about how to run application to `README.md`

### Requires:
- [x] #2

**Comment by EugeneTurkin** [comment]
Added Flask to requirements.txt.
Added a simple view function to check whether Flask was installed and functions correctly.
Ran application locally, test passed successfully. 
Updated README.
