### ISSUE TITLE
Add registration page

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/forum123#5]
In the scope of this task we need to add basic registration page without any functionality. We just need to see registration form when we to according url.

Steps to do:
- add html template with registration form in it (form fields should be: `username`, `password`)
- add flask route for registration page `/register` which renders this form
- add "Sign Up" button to the header of the base template (which will redirect to `/register`)

--------------------------------------------------------------------------------------------------

Working on this task we faced up some linter issues, next will be the description of these problems with accepted solutions:
`flake8` issues arise because it tries to lint our `.html` templates. So to disable that we need to tell `flake8` ignore these files. 
Adding this to `.flake8` config file will help:
```
exclude =
    *.html
    __pycache__
```

`mypy` issues with imports arise because some libraries doesn't have type stubs and `mypy` cannot find them via `mypy --install-types`.
To disable these errors we need to add  following lines to `.mypy` config file:
```
[mypy-flask_wtf.]
ignore_missing_imports = True

[mypy-wtforms.]
ignore_missing_imports = True
filename = ./src/*.py
```

Another `mypy` issue with subclassing `flask_wtf.FlaskForm` arises because `flask_wtf` has no type stubs and any thing imported from untyped library is considered by `mypy` as having type `Any`. Also we have a `--disallow-subclassing-any` option turned on in `mypy`. That's why we have this error.
We could get rid of this error in different ways:
- create stubs containing type hints for the `flask_wtf` library - it's the best solution, but it's really difficult and complex task
- turn off `--disallow-subclassing-any` option in `mypy`, but this will allow us to subclass anything, not only from the untyped libraries - probably not the best solution for us because we're trying to keep `mypy` to be strict as much as possible and cannot disable this option globally for all cases
- turn on `--ignore-missing-imports` option in `mypy`, it will work the same as we type `# type: ignore` for every such case - for now I'm not sure that it is best solution as well, because it will make these things implicit (but probably I'll change my mind later)
- add `# type: ignore` to exact line where error arised (at the line where we trying to subclass from `flask_wtf.FlaskForm`) - seems like it will be our choice now

So as a result of everything written above, we're going to get rid of mypy subclassing `Any` error by adding `# type: ignore` to it:
```python
class RegistrationForm(FlaskForm):  # type: ignore
    ...
```
More info about this `mypy` error you can get here:
- https://stackoverflow.com/questions/49888155/class-cannot-subclass-qobject-has-type-any-using-mypy
- https://stackoverflow.com/questions/52227841/mypy-calls-error-class-cannot-subclass-objecttype-has-type-any-on-graphen

### Requires:
- [x] #4

**Comment by EugeneTurkin** [comment]
Created a new branch (5-add-registration-page).
Installed Flask-WTF extension.
Created templates directory and base template.
Added registration and index templates.
Added view functions (aka routes/handlers?) for index and registration templates.
Created and initialized configuration file.
Installed python-dotenv and created .flasenv to simplify running up the application.
Updated requirements.txt and README.

flake8 raised several exceptions upon running it this time. Other linters showed some hard-to-comprehend errors. I also have a few questions of my own. A call to discuss all that would be great.

**Comment by birthdaysgift** [comment]
`flake8` issues arise because it tries to lint our `.html` templates. So to disable that we need to tell `flake8` ignore these files. 
Adding this to `.flake8` config file will help:
```
exclude =
    *.html
    __pycache__
```

`mypy` issues with imports arise because some libraries doesn't have type stubs and `mypy` cannot find them via `mypy --install-types`.
To disable these errors we need to add  following lines to `.mypy` config file:
```
[mypy-flask_wtf.]
ignore_missing_imports = True

[mypy-wtforms.]
ignore_missing_imports = True
[7:42 PM]
filename = ./src/*.py
```

Another `mypy` issue with subclassing `flask_wtf.FlaskForm` arises because `flask_wtf` has no type stubs and any thing imported from untyped library is considered by `mypy` as having type `Any`. Also we have a `--disallow-subclassing-any` option turned on in `mypy`. That's why we have this error.
We could get rid of this error in different ways:
- create stubs containing type hints for the `flask_wtf` library - it's the best solution, but it's really difficult and complex task
- turn off `--disallow-subclassing-any` option in `mypy`, but this will allow us to subclass anything, not only from the untyped libraries - probably not the best solution for us because we're trying to keep `mypy` to be strict as much as possible and cannot disable this option globally for all cases
- turn on `--ignore-missing-imports` option in `mypy`, it will work the same as we type `# type: ignore` for every such case - for now I'm not sure that it is best solution as well, because it will make these things implicit (but probably I'll change my mind later)
- add `# type: ignore` to exact line where error arised (at the line where we trying to subclass from `flask_wtf.FlaskForm`) - seems like it will be our choice now

So as a result of everything written above, we're going to get rid of mypy subclassing `Any` error by adding `# type: ignore` to it:
```python
class RegistrationForm(FlaskForm):  # type: ignore
    ...
```
More info about this `mypy` error you can get here:
- https://stackoverflow.com/questions/49888155/class-cannot-subclass-qobject-has-type-any-using-mypy
- https://stackoverflow.com/questions/52227841/mypy-calls-error-class-cannot-subclass-objecttype-has-type-any-on-graphen


PS: added this info to the ticket description to have it in the commit message of the final version of the pull request which will be merged to `develop`
